### ISSUE TITLE
Uses "squad" message field instead of "broadcast" on BF2042

### ISSUE THREAD

**Issue by brads93** [community-network/battlefield-anti-idle#1]
Anti-idle is selecting "squad" message field instead of using the "broadcast" option which I'm assuming was the original method. Also, is there a way to send multiple messages in the config file?

Appreciate the tool, can make hosting a portal experience much less dreadful when waiting an eternity for players to join.

**Comment by zefanjajobse** [comment]
the game has a broadcasting system, so im not sure why you need it, but updated it so it should work via broadcast

**Comment by brads93** [comment]
Just because my experience can be fun with lots of players, but getting ppl to stay in the beginning is a chore. So I sometines like to inform ppl to kill me while im afk in a 1v1 scenario and ask them to wait while other ppl join. Or to broadcast an ad when full for other servers if we host different regions, different modes etc.Thank you I'll give it a test.

**Comment by zefanjajobse** [comment]
could also change it so its configurable to both team chat and broadcast?

**Comment by brads93** [comment]
That would be great, also could muktiple messages be an option?

Brad Sinclair
Veteran, Marine Corps
267-300-2334
